#index:
#    path: /
#    controller: App\Controller\DefaultController::index
pdf:
    path: /pdf/{id}
    controller: App\Controller\PdfController::generatePdf

recharge_partie:
    path: /recharge-partie/{deckId}/{dataTab}
    controller: App\Controller\UpdateCardControlleurController::index